---
kind: List
apiVersion: v1
items:
- kind: ReplicationController
  apiVersion: v1
  metadata:
    name: kong
    labels:
      name: kong
  spec:
    replicas: 3
    selector:
      name: kong
    template:
      metadata:
        labels:
          name: kong
      spec:
        containers:
        - name: kong
          image: kong
          ports:
          - name: proxy
            containerPort: 8003
            protocol: TCP
          env:
          - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:8003, 0.0.0.0:8446 ssl"
          - name: KONG_PG_PASSWORD
            value: kong
          - name: KONG_PG_HOST
            value: postgres
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"
- kind: Service
  apiVersion: v1
  metadata:
    name: kong-admin
    labels:
      name: kong-admin
  spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 8003
      targetPort: 8003
    selector:
      name: kong
