apiVersion: batch/v1
kind: Job
metadata:
  name: kong-migration
  namespace: ss-gateway-database
spec:
  template:
    metadata:
      name: kong-migration
    spec:
      containers:
      - name: kong-migration
        image: kong
        env:
          - name: KONG_NGINX_DAEMON
            value: 'off'
          - name: KONG_PG_PASSWORD
            value: kong
          - name: KONG_PG_HOST
            value: postgres-kong.ss-gateway-database-kong.svc.cluster.local
        command: [ "/bin/sh", "-c", "kong migrations bootstrap" ]
      restartPolicy: Never