kind: Namespace
apiVersion: v1
metadata:
  name: ss-gateway-konga-ui
  labels:
    name: ss-gateway-konga-ui

---
apiVersion: v1
kind: Pod
metadata:
  name: konga-prepare
  namespace: ss-gateway-konga-ui
spec:
  containers:
  - args:
    - -c
    - prepare
    - -a
    - postgres
    - -u
    - postgresql://kong@postgres.ss-database-kong.svc.cluster.local:5432/konga_db
    name: konga-prepare
    image: pantsel/konga
  restartPolicy: OnFailure
