kind: Namespace
apiVersion: v1
metadata:
  name: ss-gateway-database-kong
  labels:
    name: ss-gateway-database-kong

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-kong
  namespace: ss-gateway-database-kong
spec:
  ports:
  - name: pgql
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres-kong

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: postgres-kong
  namespace: ss-gateway-database-kong
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: postgres-kong
    spec:
      containers:
        - name: postgres-kong
          image: postgres:9.6
          env:
            - name: POSTGRES_USER
              value: kong
            - name: POSTGRES_PASSWORD
              value: kong
            - name: POSTGRES_DB
              value: kong
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: pg-data
      volumes:
        - name: pg-data
          emptyDir: {}