kind: Namespace
apiVersion: v1
metadata:
  name: ss-gateway-kong
  labels:
    name: ss-gateway-kong

---
apiVersion: v1
kind: Service
metadata:
  name: kong-proxy
  namespace: ss-gateway-kong
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: kong-proxy
    port: 8002
    targetPort: 8002
    protocol: TCP
  - name: kong-proxy-ssl
    port: 8442
    targetPort: 8442
    protocol: TCP
  selector:
    app: kong

---
apiVersion: v1
kind: Service
metadata:
  name: kong-admin
  namespace: ss-gateway-kong
spec:
  ports:
  - name: kong-admin
    port: 8003
    targetPort: 8003
    protocol: TCP
  - name: kong-admin-ssl
    port: 8443
    targetPort: 8443
    protocol: TCP
  selector:
    app: kong

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: kong
  namespace: ss-gateway-kong
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: kong
        app: kong
    spec:
      containers:
      - name: kong
        image: kong
        env:
          - name: KONG_PROXY_LISTEN
            value: "0.0.0.0:8002, 0.0.0.0:8442 ssl"
          - name: KONG_ADMIN_LISTEN
            value: "0.0.0.0:8003, 0.0.0.0:8443 ssl"
          - name: KONG_PG_PASSWORD
            value: kong
          - name: KONG_PG_HOST
            value: postgres-kong.ss-gateway-database-kong
          - name: KONG_PROXY_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_ADMIN_ACCESS_LOG
            value: "/dev/stdout"
          - name: KONG_PROXY_ERROR_LOG
            value: "/dev/stderr"
          - name: KONG_ADMIN_ERROR_LOG
            value: "/dev/stderr"
        ports:
        - name: kong-proxy
          containerPort: 8002
          protocol: TCP
        - name: kong-admin
          containerPort: 8003
          protocol: TCP
        - name: kong-proxy-ssl
          containerPort: 8442
          protocol: TCP
        - name: kong-admin-ssl
          containerPort: 8443
          protocol: TCP