kind: Namespace
apiVersion: v1
metadata:
  name: ss-gateway-konga-ui
  labels:
    name: ss-gateway-konga-ui

---
apiVersion: batch/v1
kind: Job
metadata:
  name: konga-prepare
  namespace: ss-gateway-konga-ui
spec:
  containers:
  - name: konga-prepare
    image: pantsel/konga
    command: [ "/bin/sh", "-c", "prepare -a postgres -u postgresql://kong@postgres.ss-database-kong.svc.cluster.local:5432/konga_db" ]
  restartPolicy: Neve