kind: Namespace
apiVersion: v1
metadata:
  name: ss-gateway-konga
  labels:
    name: ss-gateway-konga

---
apiVersion: v1
kind: Service
metadata:
  name: konga-proxy
  namespace: ss-gateway-konga
spec:
  type: LoadBalancer
  loadBalancerSourceRanges:
  - 0.0.0.0/0
  ports:
  - name: konga-proxy
    port: 8004
    targetPort: 8004
    protocol: TCP
  - name: konga-proxy-ssl
    port: 8444
    targetPort: 8444
    protocol: TCP
  selector:
    app: konga

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: konga
  namespace: ss-gateway-konga
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: konga
        app: konga
    spec:
      containers:
      - name: konga
        image: pantsel/konga
        env:
          - name: DB_ADAPTER
            value: postgres
          - name: DB_HOST
            value: postgres.ss-gateway-database-postgres.svc.cluster.local
          - name: DB_USER
            value: konga
          - name: DB_PASSWORD
            value: konga
          - name: DB_DATABASE
            value: konga
          - name: NODE_ENV
            value: production
        ports:
          - name: konga-proxy
            containerPort: 8004
            protocol: TCP
          - name: konga-proxy-ssl
            containerPort: 8444
            protocol: TCP